import { Option } from '@/ui/dashboard/Select';

export const timezones: Option[] = [
  { id: 'Pacific/Midway', label: '(UTC-11:00) Midway Island, American Samoa' },
  { id: 'Pacific/Honolulu', label: '(UTC-10:00) Hawaii' },
  { id: 'America/Anchorage', label: '(UTC-09:00) Alaska' },
  { id: 'America/Tijuana', label: '(UTC-08:00) Baja California' },
  { id: 'America/Los_Angeles', label: '(UTC-08:00) Pacific Time (US and Canada)' },
  { id: 'America/Phoenix', label: '(UTC-07:00) Arizona' },
  { id: 'America/Chihuahua', label: '(UTC-07:00) Chihuahua, La Paz, Mazatlan' },
  { id: 'America/Denver', label: '(UTC-07:00) Mountain Time (US and Canada)' },
  { id: 'America/Belize', label: '(UTC-06:00) Central America' },
  { id: 'America/Chicago', label: '(UTC-06:00) Central Time (US and Canada)' },
  { id: 'America/Mexico_City', label: '(UTC-06:00) Guadalajara, Mexico City, Monterrey' },
  { id: 'America/Regina', label: '(UTC-06:00) Saskatchewan' },
  { id: 'America/Bogota', label: '(UTC-05:00) Bogota, Lima, Quito' },
  { id: 'America/Jamaica', label: '(UTC-05:00) Kingston, George Town' },
  { id: 'America/New_York', label: '(UTC-05:00) Eastern Time (US and Canada)' },
  { id: 'America/Indiana/Indianapolis', label: '(UTC-05:00) Indiana (East)' },
  { id: 'America/Caracas', label: '(UTC-04:30) Caracas' },
  { id: 'America/Asuncion', label: '(UTC-04:00) Asuncion' },
  { id: 'America/Halifax', label: '(UTC-04:00) Atlantic Time (Canada)' },
  { id: 'America/Cuiaba', label: '(UTC-04:00) Cuiaba' },
  { id: 'America/Manaus', label: '(UTC-04:00) Georgetown, La Paz, Manaus, San Juan' },
  { id: 'America/St_Johns', label: '(UTC-03:30) Newfoundland and Labrador' },
  { id: 'America/Sao_Paulo', label: '(UTC-03:00) Brasilia' },
  { id: 'America/Buenos_Aires', label: '(UTC-03:00) Buenos Aires' },
  { id: 'America/Cayenne', label: '(UTC-03:00) Cayenne, Fortaleza' },
  { id: 'America/Godthab', label: '(UTC-03:00) Greenland' },
  { id: 'America/Montevideo', label: '(UTC-03:00) Montevideo' },
  { id: 'America/Bahia', label: '(UTC-03:00) Salvador' },
  { id: 'America/Santiago', label: '(UTC-03:00) Santiago' },
  { id: 'America/Noronha', label: '(UTC-02:00) Mid-Atlantic' },
  { id: 'Atlantic/Azores', label: '(UTC-01:00) Azores' },
  { id: 'Atlantic/Cape_Verde', label: '(UTC-01:00) Cape Verde Islands' },
  { id: 'Europe/London', label: '(UTC) Dublin, Edinburgh, Lisbon, London' },
  { id: 'Africa/Casablanca', label: '(UTC) Casablanca' },
  { id: 'Africa/Monrovia', label: '(UTC) Monrovia, Reykjavik' },
  { id: 'Europe/Amsterdam', label: '(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna' },
  { id: 'Europe/Belgrade', label: '(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague' },
  { id: 'Europe/Brussels', label: '(UTC+01:00) Brussels, Copenhagen, Madrid, Paris' },
  { id: 'Europe/Warsaw', label: '(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb' },
  { id: 'Africa/Algiers', label: '(UTC+01:00) West Central Africa' },
  { id: 'Africa/Windhoek', label: '(UTC+01:00) Windhoek' },
  { id: 'Europe/Athens', label: '(UTC+02:00) Athens, Bucharest' },
  { id: 'Asia/Beirut', label: '(UTC+02:00) Beirut' },
  { id: 'Africa/Cairo', label: '(UTC+02:00) Cairo' },
  { id: 'Asia/Damascus', label: '(UTC+02:00) Damascus' },
  { id: 'EET', label: '(UTC+02:00) Eastern Europe' },
  { id: 'Africa/Harare', label: '(UTC+02:00) Harare, Pretoria' },
  { id: 'Europe/Helsinki', label: '(UTC+02:00) Helsinki, Kiev, Riga, Sofia, Tallinn, Vilnius' },
  { id: 'Asia/Istanbul', label: '(UTC+02:00) Istanbul' },
  { id: 'Asia/Jerusalem', label: '(UTC+02:00) Jerusalem' },
  { id: 'Europe/Kaliningrad', label: '(UTC+02:00) Kaliningrad' },
  { id: 'Africa/Tripoli', label: '(UTC+02:00) Tripoli' },
  { id: 'Asia/Amman', label: '(UTC+02:00) Amman' },
  { id: 'Asia/Baghdad', label: '(UTC+03:00) Baghdad' },
  { id: 'Asia/Kuwait', label: '(UTC+03:00) Kuwait, Riyadh' },
  { id: 'Europe/Minsk', label: '(UTC+03:00) Minsk' },
  { id: 'Europe/Moscow', label: '(UTC+03:00) Moscow, St. Petersburg, Volgograd' },
  { id: 'Africa/Nairobi', label: '(UTC+03:00) Nairobi' },
  { id: 'Asia/Tehran', label: '(UTC+03:30) Tehran' },
  { id: 'Asia/Muscat', label: '(UTC+04:00) Abu Dhabi, Muscat' },
  { id: 'Asia/Baku', label: '(UTC+04:00) Baku' },
  { id: 'Europe/Samara', label: '(UTC+04:00) Izhevsk, Samara' },
  { id: 'Indian/Mauritius', label: '(UTC+04:00) Port Louis' },
  { id: 'Asia/Tbilisi', label: '(UTC+04:00) Tbilisi' },
  { id: 'Asia/Yerevan', label: '(UTC+04:00) Yerevan' },
  { id: 'Asia/Kabul', label: '(UTC+04:30) Kabul' },
  { id: 'Asia/Tashkent', label: '(UTC+05:00) Tashkent, Ashgabat' },
  { id: 'Asia/Yekaterinburg', label: '(UTC+05:00) Ekaterinburg' },
  { id: 'Asia/Karachi', label: '(UTC+05:00) Islamabad, Karachi' },
  { id: 'Asia/Kolkata', label: '(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi' },
  { id: 'Asia/Colombo', label: '(UTC+05:30) Sri Jayawardenepura' },
  { id: 'Asia/Katmandu', label: '(UTC+05:45) Kathmandu' },
  { id: 'Asia/Almaty', label: '(UTC+06:00) Astana' },
  { id: 'Asia/Dhaka', label: '(UTC+06:00) Dhaka' },
  { id: 'Asia/Novosibirsk', label: '(UTC+06:00) Novosibirsk' },
  { id: 'Asia/Rangoon', label: '(UTC+06:30) Yangon (Rangoon)' },
  { id: 'Asia/Bangkok', label: '(UTC+07:00) Bangkok, Hanoi, Jakarta' },
  { id: 'Asia/Krasnoyarsk', label: '(UTC+07:00) Krasnoyarsk' },
  { id: 'Asia/Chongqing', label: '(UTC+08:00) Beijing, Chongqing, Hong Kong SAR, Urumqi' },
  { id: 'Asia/Irkutsk', label: '(UTC+08:00) Irkutsk' },
  { id: 'Asia/Kuala_Lumpur', label: '(UTC+08:00) Kuala Lumpur, Singapore' },
  { id: 'Australia/Perth', label: '(UTC+08:00) Perth' },
  { id: 'Asia/Taipei', label: '(UTC+08:00) Taipei' },
  { id: 'Asia/Ulaanbaatar', label: '(UTC+08:00) Ulaanbaatar' },
  { id: 'Asia/Tokyo', label: '(UTC+09:00) Osaka, Sapporo, Tokyo' },
  { id: 'Asia/Seoul', label: '(UTC+09:00) Seoul' },
  { id: 'Asia/Yakutsk', label: '(UTC+09:00) Yakutsk' },
  { id: 'Australia/Adelaide', label: '(UTC+09:30) Adelaide' },
  { id: 'Australia/Darwin', label: '(UTC+09:30) Darwin' },
  { id: 'Australia/Brisbane', label: '(UTC+10:00) Brisbane' },
  { id: 'Australia/Canberra', label: '(UTC+10:00) Canberra, Melbourne, Sydney' },
  { id: 'Pacific/Guam', label: '(UTC+10:00) Guam, Port Moresby' },
  { id: 'Australia/Hobart', label: '(UTC+10:00) Hobart' },
  { id: 'Asia/Magadan', label: '(UTC+10:00) Magadan' },
  { id: 'Asia/Vladivostok', label: '(UTC+10:00) Vladivostok, Magadan' },
  { id: 'Asia/Srednekolymsk', label: '(UTC+11:00) Chokirdakh' },
  { id: 'Pacific/Guadalcanal', label: '(UTC+11:00) Solomon Islands, New Caledonia' },
  { id: 'Asia/Anadyr', label: '(UTC+12:00) Anadyr, Petropavlovsk-Kamchatsky' },
  { id: 'Pacific/Auckland', label: '(UTC+12:00) Auckland, Wellington' },
  { id: 'Pacific/Fiji', label: '(UTC+12:00) Fiji Islands, Kamchatka, Marshall Islands' },
  { id: 'Pacific/Tongatapu', label: "(UTC+13:00) Nuku'alofa" },
  { id: 'Pacific/Apia', label: '(UTC+13:00) Samoa' },
];
