export enum AppEvent {
  GetHotkeys = 'get-hotkeys',
  GetSettings = 'get-settings',
  GetThemeCss = 'get-theme-css',
  GetTranslations = 'get-translations',
  HideSelect = 'hide-select',
  RegisterServiceConfig = 'register-service-config',
  SelectChange = 'select-change',
  SelectOption = 'select-option',
  ServiceConfigChange = 'service-config-change',
  SetSelectBounds = 'set-select-bounds',
  SetSelectItems = 'set-select-items',
  SetServiceConfigItem = 'set-service-config-item',
  ShowSelect = 'show-select',
  ThemeCssChange = 'theme-css-change',
}
