export type HotkeyCommand =
  | 'addNote'
  | 'completeTaskEarly'
  | 'continueTask'
  | 'createTask'
  | 'externalDistraction'
  | 'internalDistraction'
  | 'moveTask'
  | 'openInBrowser'
  | 'pauseTimer'
  | 'routeHome'
  | 'routeProductivity'
  | 'routeSettings'
  | 'skipBreak'
  | 'startTimer'
  | 'switchTask'
  | 'toggleMenu'
  | 'voidTask';
