import { SetItem } from '@tinynudge/pomello-service';
import { CustomSound } from './CustomSound';

export interface Settings {
  alwaysOnTop: boolean;
  snapEdges: boolean;
  timeExpiredNotification: string;
  overtime: boolean;
  overtimeDelay: number;
  checkPomelloStatus: boolean;
  warnBeforeTaskCancel: boolean;
  warnBeforeAppQuit: boolean;
  taskTime: number;
  shortBreakTime: number;
  longBreakTime: number;
  pomodoroSet: number | SetItem[];
  resetPomodoroSet: boolean;
  autoStartTasks: boolean;
  autoStartBreaks: boolean;
  titleMarker: string;
  titleFormat: string;
  completedTaskPosition: string;
  createdTaskPosition: string;
  productivityChartType: string;
  productivityChartDays: string[];
  betweenTasksGracePeriod: number;
  longBreakTimerEndSound: string | null;
  longBreakTimerEndVol: number | string;
  longBreakTimerStartSound: string | null;
  longBreakTimerStartVol: number | string;
  longBreakTimerTickSound: string | null;
  longBreakTimerTickVol: number | string;
  osxAllowMoveAnywhere: boolean;
  selectMaxRows: number;
  shortBreakTimerEndSound: string | null;
  shortBreakTimerEndVol: number | string;
  shortBreakTimerStartSound: string | null;
  shortBreakTimerStartVol: number | string;
  shortBreakTimerTickSound: string | null;
  shortBreakTimerTickVol: number | string;
  showAddNoteButton: boolean;
  showMenuButton: boolean;
  showPauseButton: boolean;
  showSwitchTaskButton: boolean;
  showTaskFinishedButton: boolean;
  showVoidTaskButton: boolean;
  taskTimerEndSound: string | null;
  taskTimerEndVol: number | string;
  taskTimerStartSound: string | null;
  taskTimerStartVol: number | string;
  taskTimerTickSound: string | null;
  taskTimerTickVol: number | string;
  sounds: Record<string, CustomSound | undefined>;
  timestamp?: number;
}
