name: Release alpha

on: workflow_dispatch

jobs:
  draft:
    runs-on: ubuntu-latest

    outputs:
      commit-hash: ${{ steps.commit-hash.outputs.hash }}

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Create Alpha Release
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.email "bot@pomelloapp.com"
          git config --global user.name "pomello[bot]"
          npx standard-version --prerelease alpha --skip.tag --skip.changelog
          git push --follow-tags origin main

      - name: Get Latest Commit Hash
        id: commit-hash
        run: echo "hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

  create-artifacts:
    needs: draft

    uses: ./.github/workflows/create-artifacts.yml
    with:
      APP_URL: ${{ vars.APP_URL_QA }}
      COMMIT_HASH: ${{ needs.draft.outputs.commit-hash }}
      SNAPCRAFT_CHANNEL: edge
    secrets:
      APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
      APPLE_API_ISSUER: ${{ secrets.APPLE_API_ISSUER }}
      APPLE_API_KEY: ${{ secrets.APPLE_API_KEY }}
      AUTO_UPDATE_URL: ${{ secrets.AUTO_UPDATE_URL }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
      OSX_CODE_SIGN_CERT_PASSWORD: ${{ secrets.OSX_CODE_SIGN_CERT_PASSWORD }}
      OSX_CODE_SIGN_CERT: ${{ secrets.OSX_CODE_SIGN_CERT }}
      S3_RELEASE_BUCKET: ${{ secrets.S3_RELEASE_BUCKET }}
      SNAPCRAFT_TOKEN: ${{ secrets.SNAPCRAFT_TOKEN }}
