name: Verify

on: pull_request

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '22.17.0'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10

      - name: Checkout branch
        uses: actions/checkout@v4.2.2

      - name: Cache node_modules
        uses: actions/cache@v4.2.3
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Format
        run: pnpm format:check

      - name: Lint
        run: pnpm lint

      - name: Types
        run: pnpm typecheck

      - name: Test
        run: pnpm test
        env:
          VITE_APP_URL: https://test.pomello.com
